### ISSUE TITLE
Failed to Activate rhyming-dictionary package

### ISSUE THREAD

**Issue by idealsceneprod** [partials-music/atom-rhyming-dictionary#5]
I had a single word selected in a .md file. Went to Packages / Rhyming Dictionary / Find Rhymes and it tanked.

Cannot set property 'nlp_compromise' of undefined
Hide Stack Trace
TypeError: Cannot set property 'nlp_compromise' of undefined
    at Object.24../fns.js (D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\node_modules\nlp_compromise\builds\nlp_compromise.js:2017:23)
    at s (D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\node_modules\nlp_compromise\builds\nlp_compromise.js:2:628)
    at e (D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\node_modules\nlp_compromise\builds\nlp_compromise.js:2:799)
    at D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\node_modules\nlp_compromise\builds\nlp_compromise.js:2:817
    at a (D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\node_modules\nlp_compromise\builds\nlp_compromise.js:2:88)
    at Object.<anonymous> (D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\node_modules\nlp_compromise\builds\nlp_compromise.js:2:330)
    at Object.<anonymous> (D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\node_modules\nlp_compromise\builds\nlp_compromise.js:9673:3)
    at Module.get_Module._compile (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///D:/PortableApps/AtomPortable/App/Atom/resources/app.asar/static/index.js:47:45)
    at require (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\native-compile-cache.js:66:33)
    at webpackUniversalModuleDefinition (D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\lib\nlp-rhymes-async.js:3:75)
    at Object.<anonymous> (D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\lib\nlp-rhymes-async.js:10:3)
    at Object.<anonymous> (D:\PortableApps\AtomPortable\Data\atom\packages\rhyming-dictionary\node_modules\nlp-rhymes-async\lib\nlp-rhymes-async.js:48136:3)
    at Module.get_Module._compile (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///D:/PortableApps/AtomPortable/App/Atom/resources/app.asar/static/index.js:47:45)
    at require (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (file:///D:/PortableApps/AtomPortable/Data/atom/packages/rhyming-dictionary/lib/rhyming-dictionary.js:3:33)
    at Object.<anonymous> (file:///D:/PortableApps/AtomPortable/Data/atom/packages/rhyming-dictionary/lib/rhyming-dictionary.js:7:39)
    at Module.get_Module._compile (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///D:/PortableApps/AtomPortable/App/Atom/resources/app.asar/static/index.js:47:45)
    at require (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (file:///D:/PortableApps/AtomPortable/Data/atom/packages/rhyming-dictionary/lib/index.js:3:41)
    at Object.<anonymous> (file:///D:/PortableApps/AtomPortable/Data/atom/packages/rhyming-dictionary/lib/index.js:59:19)
    at Module.get_Module._compile (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///D:/PortableApps/AtomPortable/App/Atom/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (D:\PortableApps\AtomPortable\App\Atom\resources\app\static\<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\package.js:937:35)
    at Package.module.exports.Package.activateNow (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\package.js:244:22)
    at D:\PortableApps\AtomPortable\App\Atom\resources\app\src\package.js:1022:31
    at Function.module.exports.Emitter.simpleDispatch (D:\PortableApps\AtomPortable\App\Atom\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:\PortableApps\AtomPortable\App\Atom\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\command-registry.js:360:24)
    at CommandRegistry.dispatch (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\atom-environment.js:1393:34)
    at EventEmitter.outerCallback (D:\PortableApps\AtomPortable\App\Atom\resources\app\src\application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

**Comment by jaymgrt** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [rhyming-dictionary](https://github.com/partials-dev/rhyming-dictionary) package 0.3.2


### Stack Trace

Failed to activate the rhyming-dictionary package

```
At Cannot set property 'nlp_compromise' of undefined

TypeError: Cannot set property 'nlp_compromise' of undefined
    at /packages/rhyming-dictionary/node_modules/nlp-rhymes-async/node_modules/nlp_compromise/builds/nlp_compromise.js:2017:23)
    at /packages/rhyming-dictionary/node_modules/nlp-rhymes-async/node_modules/nlp_compromise/builds/nlp_compromise.js:2:628)
    at /packages/rhyming-dictionary/node_modules/nlp-rhymes-async/node_modules/nlp_compromise/builds/nlp_compromise.js:2:799)
    at /packages/rhyming-dictionary/node_modules/nlp-rhymes-async/node_modules/nlp_compromise/builds/nlp_compromise.js:2:817
    at /packages/rhyming-dictionary/node_modules/nlp-rhymes-async/node_modules/nlp_compromise/builds/nlp_compromise.js:2:88)
    at /packages/rhyming-dictionary/node_modules/nlp-rhymes-async/node_modules/nlp_compromise/builds/nlp_compromise.js:2:330)
    at /packages/rhyming-dictionary/node_modules/nlp-rhymes-async/node_modules/nlp_compromise/builds/nlp_compromise.js:9673:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at webpackUniversalModuleDefinition (/packages/rhyming-dictionary/node_modules/nlp-rhymes-async/lib/nlp-rhymes-async.js:3:75)
    at /packages/rhyming-dictionary/node_modules/nlp-rhymes-async/lib/nlp-rhymes-async.js:10:3)
    at /packages/rhyming-dictionary/node_modules/nlp-rhymes-async/lib/nlp-rhymes-async.js:48136:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/rhyming-dictionary/lib/rhyming-dictionary.js:3:33)
    at /packages/rhyming-dictionary/lib/rhyming-dictionary.js:7:39)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/rhyming-dictionary/lib/index.js:3:41)
    at /packages/rhyming-dictionary/lib/index.js:59:19)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:641362)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3029314)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017448)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1717)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:349649)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:671099)
    at EventEmitter.t (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:678566)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  6x -0:31.4.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -0:17.4.0 rhyming-dictionary:find-rhymes (div.highlights)
```

### Non-Core Packages

```
rhyming-dictionary 0.3.2 
teletype 0.13.3 
```
